### ISSUE TITLE
[BUG] `extend_exclude` only works with OS-specific paths, and not in `exclude`

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#101]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3.7
 - djLint Version: 0.5.7

## Issue
Using a "pure path" using `/` value in `extend_exclude` does not match files on Windows.  Currently it needs to have values like `foo\\bar.html`.  Using Windows directory separators then wont match the same file on Mac/Linux

Also worth noting that using `foo\\car.html` in `extend` results in another type of error, as special characters are then sent to the regex engine. e.g.
```py
Traceback (most recent call last):
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\Scripts\djlint.exe\__main__.py", line 7, in <module>
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\djlint\__init__.py", line 236, in main
    file_list = get_src([Path(x) for x in src], config)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\djlint\__init__.py", line 52, in get_src
    list(item.glob(f"**/*.{extension}")),
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\djlint\__init__.py", line 51, in <lambda>
    lambda x: not re.search(config.exclude, str(x), re.VERBOSE),
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\re.py", line 183, in search
    return _compile(pattern, flags).search(string)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\sre_parse.py", line 402, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \c at position 16
```

**Comment by jayvdb** [comment]
ping @matthiask , maybe you want to take a look at this one.  If you dont have time, I can get to it in the next 24 hrs.

**Comment by matthiask** [comment]
I didn't change the `paths.extend(...)` statement at all; I'm not sure but maybe paths should be normalized somewhere?

> Also worth noting that using foo\\car.html in extend results in another type of error, as special characters are then sent to the regex engine. e.g.

`extend_exclude` values are passed through `re.escape` but I now see that `extend` values aren't. This difference is quite definitely unintentional.

(I'm trying not to work this week, so I won't attempt to fix this in the next few days at least.)
