### ISSUE TITLE
Error in  click.get_terminal_size().columns

### ISSUE THREAD

**Issue by martinberoiz** [Riverside-Healthcare/djlint#5]
Hello,

I tried using the linter but I get an error immediately.
I use python 3.8 and I'm on a Mac. The error seems to be related to my terminal.

        Linting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00
        
        Traceback (most recent call last):
          File "/Users/martin/.virtualenvs/gwoscweb/bin/djlint", line 8, in <module>
            sys.exit(main())
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/click/core.py", line 829, in __call__
            return self.main(*args, **kwargs)
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/click/core.py", line 782, in main
            rv = self.invoke(ctx)
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
            return ctx.invoke(self.callback, **ctx.params)
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/click/core.py", line 610, in invoke
            return callback(*args, **kwargs)
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/djlint/__init__.py", line 298, in main
            error_count += build_output(error)
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/djlint/__init__.py", line 61, in build_output
            width = click.get_terminal_size().columns
        AttributeError: 'tuple' object has no attribute 'columns'

**Comment by christopherpickering** [comment]
Thanks for trying it out! What terminal do you use? the built in Mac Terminal, or something different?

**Comment by christopherpickering** [comment]
I've updated the terminal size from a dict to tuple in https://github.com/Riverside-Healthcare/djlint/commit/4c6278a6e763a61db77201e333c417eb7e117447, I'll make a new release shortly.

**Comment by martinberoiz** [comment]
I use iTerm (it’s not the built-in term app for Mac)

**Comment by christopherpickering** [comment]
Ok nice, I tried it out in iterm and didn't get the problem. I wonder if its coming from an old click version. Anyways, hopefully the latest release fixed it! 

I wish Terminus had the same password manager as iterm!

**Comment by martinberoiz** [comment]
This is great! Thank you for your quick reply. It is working well now.

**Comment by martinberoiz** [comment]
The --reformat option still throws the same exception
      
        djlint myfile.html --reformat
        
        Reformatting 1/1 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:00
        
        Traceback (most recent call last):
          File "/Users/martin/.virtualenvs/gwoscweb/bin/djlint", line 8, in <module>
            sys.exit(main())
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/click/core.py", line 829, in __call__
            return self.main(*args, **kwargs)
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/click/core.py", line 782, in main
            rv = self.invoke(ctx)
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
            return ctx.invoke(self.callback, **ctx.params)
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/click/core.py", line 610, in invoke
            return callback(*args, **kwargs)
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/djlint/__init__.py", line 287, in main
            error_count += build_check_output(error, quiet)
          File "/Users/martin/.virtualenvs/gwoscweb/lib/python3.8/site-packages/djlint/__init__.py", line 97, in build_check_output
            width = click.get_terminal_size().columns
        AttributeError: 'tuple' object has no attribute 'columns'

**Comment by christopherpickering** [comment]
Thanks! My bad 🤦🏽 Should be good now.
