### ISSUE TITLE
[BUG] --reformat causes UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 4350: invalid continuation byte

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#53]
- [x] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## System Info
 - OS: Windows
 - Python Version: 3,7
 - djLint Version: 0.4.9

## Issue
After running reformat, running it again causes an exception without informing me which file was the cause.

```py
$ djlint --reformat .

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\djlint\reformat.py", line 17, in reformat_file
    rawcode = this_file.read_text(encoding="utf8")
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\pathlib.py", line 1217, in read_text
    return f.read()
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 4350: invalid continuation byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\Scripts\djlint.exe\__main__.py", line 7, in <module>
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\djlint\__init__.py", line 298, in main
    file_errors.append(future.result())
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 4350: invalid continuation byte
```

## How To Reproduce
No idea, as the filename isnt given in the stderr.

**Comment by jayvdb** [comment]
Hacked at reformat a bit to show the filename, and found the problem

```html
{% if notice.verb == 'validación completa' or notice.verb == 'completed validation' %}
...
{% endif %}
```

becomes a reformatted

```html
{% if notice.verb == 'validaci<F3>n completa' or notice.verb == 'completed validation' %}
...
{% endif %}
```

where `<F3>` is unicode junk.

**Comment by christopherpickering** [comment]
Nice, thanks, the files are all reading as utf-8 w/ Pathlib, I wonder if there is a way to accept accent chars. I'm surprised it didn't accept the ó!

**Comment by christopherpickering** [comment]
It would be nice it it printed what file caused the crash as well :)

**Comment by jayvdb** [comment]
It did read the accent char the first time, and then it wrote out utf8 garbage, preventing reading the second time.  Something in the middle is not unicode-aware.

**Comment by christopherpickering** [comment]
Yeah, I'm thinking its line 27 in "reformat.py", if you are in the source, can you try to change that line to 
```py
this_file.write_text(beautified_code, encoding="utf8")
```
(added encoding) and see if it works for you?

If not, I'll dig up a windows and try it out as well.

**Comment by jayvdb** [comment]
:+1: Adding that to `reformat.py` fixed the problem.

**Comment by christopherpickering** [comment]
nice, thanks! I have it in a commit now and it will be in the next release.

**Comment by jayvdb** [comment]
My change to help find the problem was:

```diff
-    rawcode = this_file.read_text(encoding="utf8")
+    try:
+        rawcode = this_file.read_text(encoding="utf8")
+    except UnicodeDecodeError as e:
+        return {this_file: f"Error in {this_file}: {e}"}
```

Probably not acceptable as-is.
