### ISSUE TITLE
[BUG] IndexError: string index out of range

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#71]
- [ ] I'm on the [latest version](https://pypi.org/project/djlint/) of djLint
- [ ] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [ ] I've read the [docs](https://djlint.com)

## System Info
 - OS: e.g. ubuntu 20.04
 - Python Version (``python --version``)
 - djLint Version (``djlint --version``)

## Issue
Running `djlint .` on Windows is failing with `IndexError: string index out of range` , without indicating which file is failing.

```
$ djlint .

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\djlint\lint.py", line 84, in lint_file
    if match.group(1).split(" ")[0][0] != "/":
IndexError: string index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\Scripts\djlint.exe\__main__.py", line 7, in <module>
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\site-packages\djlint\__init__.py", line 301, in main
    file_errors.append(future.result())
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Users\vandjohn\Downloads\WPy64-3771\python-3.7.7.amd64\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
IndexError: string index out of range
```

**Comment by christopherpickering** [comment]
Yes please! It must be a tag not matching the regex. I've changed the regex and added a catch for this error, but I'd like to see what tag was throwing the error.

**Comment by Golpe82** [comment]
oh, i reinstalled it and now it is working...

**Comment by christopherpickering** [comment]
Thanks, yeah sorry, I fixed the bug and made a release sometime later.
